"use client";

import { useState } from "react";
import type { Summary } from "@/lib/types";

export default function SummaryPanel({ summary }: { summary: Summary }) {
  const [expanded, setExpanded] = useState(true);

  const confidenceColor: Record<string, string> = {
    high: "text-angel-green",
    medium: "text-amber-400",
    low: "text-angel-red",
  };

  return (
    <div className="rounded-xl border border-angel-accent/20 bg-angel-accent/5 overflow-hidden">
      {/* Header */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-angel-accent/10 transition-colors"
      >
        <div className="flex items-center gap-2">
          <span className="text-angel-accent font-medium text-sm">AI Summary</span>
          <span className={`text-xs font-mono ${confidenceColor[summary.confidence] || "text-angel-muted"}`}>
            [{summary.confidence} confidence]
          </span>
        </div>
        <span className="text-angel-muted text-sm">{expanded ? "Collapse" : "Expand"}</span>
      </button>

      {/* Content */}
      {expanded && (
        <div className="px-4 pb-4">
          <p className="text-sm text-angel-text/90 leading-relaxed whitespace-pre-wrap">
            {summary.text}
          </p>

          {/* Citations */}
          {summary.citations.length > 0 && (
            <div className="mt-3 pt-3 border-t border-angel-border">
              <span className="text-xs text-angel-muted block mb-1">Sources:</span>
              <div className="flex flex-wrap gap-2">
                {summary.citations.map((cite, i) => (
                  <a
                    key={cite.doc_id}
                    href={cite.url}
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="text-xs px-2 py-1 rounded-md bg-angel-surface border border-angel-border text-angel-accent hover:border-angel-accent/30 transition-colors"
                  >
                    [{i + 1}] {cite.title.slice(0, 40)}{cite.title.length > 40 ? "..." : ""}
                  </a>
                ))}
              </div>
            </div>
          )}

          {/* Model info */}
          {summary.model_used && (
            <span className="text-xs text-angel-muted/50 mt-2 block font-mono">
              Generated by {summary.model_used}
            </span>
          )}
        </div>
      )}
    </div>
  );
}
